#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 79
#define LARGE_STATE_COUNT 21
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_BSLASH = 1,
  anon_sym_T = 2,
  anon_sym_B = 3,
  anon_sym_P = 4,
  aux_sym_identifier_token1 = 5,
  aux_sym_identifier_token2 = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_value_token1 = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COLON = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  sym_word = 13,
  anon_sym_DASH = 14,
  anon_sym_AT = 15,
  anon_sym_DOLLAR = 16,
  anon_sym_PERCENT = 17,
  anon_sym_CARET = 18,
  anon_sym_AMP = 19,
  anon_sym_STAR = 20,
  anon_sym__ = 21,
  anon_sym_PLUS = 22,
  anon_sym_EQ = 23,
  anon_sym_TILDE = 24,
  anon_sym_BQUOTE = 25,
  sym_h1 = 26,
  sym_h2 = 27,
  sym_h3 = 28,
  sym_h4 = 29,
  sym_h5 = 30,
  sym_h6 = 31,
  sym_period = 32,
  sym_semicolon = 33,
  sym_fslash = 34,
  sym_question_mark = 35,
  sym_exclamation_point = 36,
  sym_bold = 37,
  sym_italics = 38,
  sym_emdash = 39,
  sym_underline = 40,
  sym_reference = 41,
  sym_document = 42,
  sym_title = 43,
  sym_heading = 44,
  sym_bookmark = 45,
  sym_paragraph = 46,
  sym_identifier = 47,
  sym_parameter = 48,
  sym_value = 49,
  sym_function = 50,
  sym_hyphen = 51,
  sym_style_marker = 52,
  sym_sentence = 53,
  sym_fragment = 54,
  sym_end = 55,
  sym_punctuation = 56,
  sym__surround = 57,
  sym_quote = 58,
  sym_parentheses = 59,
  sym_other = 60,
  sym_comma = 61,
  sym_colon = 62,
  aux_sym_document_repeat1 = 63,
  aux_sym_title_repeat1 = 64,
  aux_sym_function_repeat1 = 65,
  aux_sym_hyphen_repeat1 = 66,
  aux_sym_sentence_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_T] = "T",
  [anon_sym_B] = "B",
  [anon_sym_P] = "P",
  [aux_sym_identifier_token1] = "identifier_token1",
  [aux_sym_identifier_token2] = "identifier_token2",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_value_token1] = "value_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_word] = "word",
  [anon_sym_DASH] = "-",
  [anon_sym_AT] = "@",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_PERCENT] = "%",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_PLUS] = "+",
  [anon_sym_EQ] = "=",
  [anon_sym_TILDE] = "~",
  [anon_sym_BQUOTE] = "`",
  [sym_h1] = "h1",
  [sym_h2] = "h2",
  [sym_h3] = "h3",
  [sym_h4] = "h4",
  [sym_h5] = "h5",
  [sym_h6] = "h6",
  [sym_period] = "period",
  [sym_semicolon] = "semicolon",
  [sym_fslash] = "fslash",
  [sym_question_mark] = "question_mark",
  [sym_exclamation_point] = "exclamation_point",
  [sym_bold] = "bold",
  [sym_italics] = "italics",
  [sym_emdash] = "emdash",
  [sym_underline] = "underline",
  [sym_reference] = "reference",
  [sym_document] = "document",
  [sym_title] = "title",
  [sym_heading] = "heading",
  [sym_bookmark] = "bookmark",
  [sym_paragraph] = "paragraph",
  [sym_identifier] = "identifier",
  [sym_parameter] = "parameter",
  [sym_value] = "value",
  [sym_function] = "function",
  [sym_hyphen] = "hyphen",
  [sym_style_marker] = "style_marker",
  [sym_sentence] = "sentence",
  [sym_fragment] = "fragment",
  [sym_end] = "end",
  [sym_punctuation] = "punctuation",
  [sym__surround] = "_surround",
  [sym_quote] = "quote",
  [sym_parentheses] = "parentheses",
  [sym_other] = "other",
  [sym_comma] = "comma",
  [sym_colon] = "colon",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_title_repeat1] = "title_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
  [aux_sym_hyphen_repeat1] = "hyphen_repeat1",
  [aux_sym_sentence_repeat1] = "sentence_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_T] = anon_sym_T,
  [anon_sym_B] = anon_sym_B,
  [anon_sym_P] = anon_sym_P,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [aux_sym_identifier_token2] = aux_sym_identifier_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_word] = sym_word,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_h1] = sym_h1,
  [sym_h2] = sym_h2,
  [sym_h3] = sym_h3,
  [sym_h4] = sym_h4,
  [sym_h5] = sym_h5,
  [sym_h6] = sym_h6,
  [sym_period] = sym_period,
  [sym_semicolon] = sym_semicolon,
  [sym_fslash] = sym_fslash,
  [sym_question_mark] = sym_question_mark,
  [sym_exclamation_point] = sym_exclamation_point,
  [sym_bold] = sym_bold,
  [sym_italics] = sym_italics,
  [sym_emdash] = sym_emdash,
  [sym_underline] = sym_underline,
  [sym_reference] = sym_reference,
  [sym_document] = sym_document,
  [sym_title] = sym_title,
  [sym_heading] = sym_heading,
  [sym_bookmark] = sym_bookmark,
  [sym_paragraph] = sym_paragraph,
  [sym_identifier] = sym_identifier,
  [sym_parameter] = sym_parameter,
  [sym_value] = sym_value,
  [sym_function] = sym_function,
  [sym_hyphen] = sym_hyphen,
  [sym_style_marker] = sym_style_marker,
  [sym_sentence] = sym_sentence,
  [sym_fragment] = sym_fragment,
  [sym_end] = sym_end,
  [sym_punctuation] = sym_punctuation,
  [sym__surround] = sym__surround,
  [sym_quote] = sym_quote,
  [sym_parentheses] = sym_parentheses,
  [sym_other] = sym_other,
  [sym_comma] = sym_comma,
  [sym_colon] = sym_colon,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_title_repeat1] = aux_sym_title_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
  [aux_sym_hyphen_repeat1] = aux_sym_hyphen_repeat1,
  [aux_sym_sentence_repeat1] = aux_sym_sentence_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_T] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_B] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_P] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_h1] = {
    .visible = true,
    .named = true,
  },
  [sym_h2] = {
    .visible = true,
    .named = true,
  },
  [sym_h3] = {
    .visible = true,
    .named = true,
  },
  [sym_h4] = {
    .visible = true,
    .named = true,
  },
  [sym_h5] = {
    .visible = true,
    .named = true,
  },
  [sym_h6] = {
    .visible = true,
    .named = true,
  },
  [sym_period] = {
    .visible = true,
    .named = true,
  },
  [sym_semicolon] = {
    .visible = true,
    .named = true,
  },
  [sym_fslash] = {
    .visible = true,
    .named = true,
  },
  [sym_question_mark] = {
    .visible = true,
    .named = true,
  },
  [sym_exclamation_point] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italics] = {
    .visible = true,
    .named = true,
  },
  [sym_emdash] = {
    .visible = true,
    .named = true,
  },
  [sym_underline] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_bookmark] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_hyphen] = {
    .visible = true,
    .named = true,
  },
  [sym_style_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_end] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym__surround] = {
    .visible = false,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_parentheses] = {
    .visible = true,
    .named = true,
  },
  [sym_other] = {
    .visible = true,
    .named = true,
  },
  [sym_comma] = {
    .visible = true,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_title_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hyphen_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 4,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '!', 41,
        '"', 11,
        '$', 21,
        '%', 22,
        '&', 24,
        '(', 14,
        ')', 17,
        '*', 25,
        '+', 27,
        ',', 16,
        '-', 19,
        '.', 37,
        '/', 39,
        ':', 15,
        ';', 38,
        '=', 28,
        '?', 40,
        '@', 20,
        'B', 7,
        'H', 1,
        'P', 8,
        'T', 6,
        '\\', 5,
        '^', 23,
        '_', 26,
        '`', 30,
        '~', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '1') ADVANCE(31);
      if (lookahead == '2') ADVANCE(32);
      if (lookahead == '3') ADVANCE(33);
      if (lookahead == '4') ADVANCE(34);
      if (lookahead == '5') ADVANCE(35);
      if (lookahead == '6') ADVANCE(36);
      END_STATE();
    case 2:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(13);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '!', 41,
        '"', 11,
        '$', 21,
        '%', 22,
        '&', 24,
        '(', 14,
        ')', 17,
        '*', 25,
        '+', 27,
        ',', 16,
        '-', 19,
        '.', 37,
        '/', 39,
        ':', 15,
        ';', 38,
        '=', 28,
        '?', 40,
        '@', 20,
        '\\', 5,
        '^', 23,
        '_', 26,
        '`', 30,
        '~', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('\'' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_T);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_B);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_P);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(44);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(46);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(42);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(45);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_h1);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_h2);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_h3);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_h4);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_h5);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_h6);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_period);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_semicolon);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_fslash);
      if (lookahead == '/') ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_question_mark);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_exclamation_point);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_bold);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_italics);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_emdash);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_underline);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_reference);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 10},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 10},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_T] = ACTIONS(1),
    [anon_sym_B] = ACTIONS(1),
    [anon_sym_P] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_h1] = ACTIONS(1),
    [sym_h2] = ACTIONS(1),
    [sym_h3] = ACTIONS(1),
    [sym_h4] = ACTIONS(1),
    [sym_h5] = ACTIONS(1),
    [sym_h6] = ACTIONS(1),
    [sym_period] = ACTIONS(1),
    [sym_semicolon] = ACTIONS(1),
    [sym_fslash] = ACTIONS(1),
    [sym_question_mark] = ACTIONS(1),
    [sym_exclamation_point] = ACTIONS(1),
    [sym_bold] = ACTIONS(1),
    [sym_italics] = ACTIONS(1),
    [sym_emdash] = ACTIONS(1),
    [sym_underline] = ACTIONS(1),
    [sym_reference] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(78),
    [sym_title] = STATE(38),
    [sym_heading] = STATE(38),
    [sym_bookmark] = STATE(38),
    [sym_paragraph] = STATE(38),
    [sym_function] = STATE(38),
    [aux_sym_document_repeat1] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BSLASH] = ACTIONS(5),
  },
  [2] = {
    [sym_hyphen] = STATE(16),
    [sym_style_marker] = STATE(16),
    [sym_sentence] = STATE(19),
    [sym_fragment] = STATE(74),
    [sym_punctuation] = STATE(16),
    [sym__surround] = STATE(16),
    [sym_quote] = STATE(16),
    [sym_parentheses] = STATE(16),
    [sym_other] = STATE(16),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(19),
    [aux_sym_sentence_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(7),
    [anon_sym_BQUOTE] = ACTIONS(7),
    [sym_period] = ACTIONS(7),
    [sym_semicolon] = ACTIONS(7),
    [sym_fslash] = ACTIONS(9),
    [sym_question_mark] = ACTIONS(7),
    [sym_exclamation_point] = ACTIONS(7),
    [sym_bold] = ACTIONS(7),
    [sym_italics] = ACTIONS(7),
    [sym_emdash] = ACTIONS(7),
    [sym_underline] = ACTIONS(7),
    [sym_reference] = ACTIONS(7),
  },
  [3] = {
    [sym_hyphen] = STATE(16),
    [sym_style_marker] = STATE(16),
    [sym_sentence] = STATE(19),
    [sym_fragment] = STATE(74),
    [sym_punctuation] = STATE(16),
    [sym__surround] = STATE(16),
    [sym_quote] = STATE(16),
    [sym_parentheses] = STATE(16),
    [sym_other] = STATE(16),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(19),
    [aux_sym_sentence_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_BSLASH] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [sym_period] = ACTIONS(11),
    [sym_semicolon] = ACTIONS(11),
    [sym_fslash] = ACTIONS(13),
    [sym_question_mark] = ACTIONS(11),
    [sym_exclamation_point] = ACTIONS(11),
    [sym_bold] = ACTIONS(11),
    [sym_italics] = ACTIONS(11),
    [sym_emdash] = ACTIONS(11),
    [sym_underline] = ACTIONS(11),
    [sym_reference] = ACTIONS(11),
  },
  [4] = {
    [sym_hyphen] = STATE(5),
    [sym_style_marker] = STATE(5),
    [sym_end] = STATE(36),
    [sym_punctuation] = STATE(5),
    [sym__surround] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_parentheses] = STATE(5),
    [sym_other] = STATE(5),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_sentence_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_period] = ACTIONS(31),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_question_mark] = ACTIONS(31),
    [sym_exclamation_point] = ACTIONS(31),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [5] = {
    [sym_hyphen] = STATE(5),
    [sym_style_marker] = STATE(5),
    [sym_punctuation] = STATE(5),
    [sym__surround] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_parentheses] = STATE(5),
    [sym_other] = STATE(5),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_sentence_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_BSLASH] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_COLON] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(50),
    [anon_sym_RPAREN] = ACTIONS(39),
    [sym_word] = ACTIONS(53),
    [anon_sym_AT] = ACTIONS(56),
    [anon_sym_DOLLAR] = ACTIONS(56),
    [anon_sym_PERCENT] = ACTIONS(56),
    [anon_sym_CARET] = ACTIONS(56),
    [anon_sym_AMP] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(59),
    [anon_sym__] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(56),
    [anon_sym_EQ] = ACTIONS(56),
    [anon_sym_TILDE] = ACTIONS(56),
    [anon_sym_BQUOTE] = ACTIONS(56),
    [sym_period] = ACTIONS(39),
    [sym_semicolon] = ACTIONS(62),
    [sym_fslash] = ACTIONS(65),
    [sym_question_mark] = ACTIONS(39),
    [sym_exclamation_point] = ACTIONS(39),
    [sym_bold] = ACTIONS(68),
    [sym_italics] = ACTIONS(68),
    [sym_emdash] = ACTIONS(62),
    [sym_underline] = ACTIONS(68),
    [sym_reference] = ACTIONS(68),
  },
  [6] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(11),
    [sym_fragment] = STATE(49),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(11),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(71),
    [anon_sym_BSLASH] = ACTIONS(71),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [7] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(10),
    [sym_fragment] = STATE(53),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(10),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(73),
    [anon_sym_BSLASH] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [8] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(12),
    [sym_fragment] = STATE(44),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(12),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_BSLASH] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [9] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(12),
    [sym_fragment] = STATE(52),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(12),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_BSLASH] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [10] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(12),
    [sym_fragment] = STATE(46),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(12),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(79),
    [anon_sym_BSLASH] = ACTIONS(79),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [11] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(12),
    [sym_fragment] = STATE(45),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(12),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_BSLASH] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [12] = {
    [sym_hyphen] = STATE(18),
    [sym_style_marker] = STATE(18),
    [sym_sentence] = STATE(12),
    [sym_punctuation] = STATE(18),
    [sym__surround] = STATE(18),
    [sym_quote] = STATE(18),
    [sym_parentheses] = STATE(18),
    [sym_other] = STATE(18),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(12),
    [aux_sym_sentence_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(83),
    [anon_sym_BSLASH] = ACTIONS(83),
    [anon_sym_DQUOTE] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(88),
    [anon_sym_COLON] = ACTIONS(91),
    [anon_sym_COMMA] = ACTIONS(94),
    [anon_sym_RPAREN] = ACTIONS(83),
    [sym_word] = ACTIONS(97),
    [anon_sym_AT] = ACTIONS(100),
    [anon_sym_DOLLAR] = ACTIONS(100),
    [anon_sym_PERCENT] = ACTIONS(100),
    [anon_sym_CARET] = ACTIONS(100),
    [anon_sym_AMP] = ACTIONS(103),
    [anon_sym_STAR] = ACTIONS(103),
    [anon_sym__] = ACTIONS(103),
    [anon_sym_PLUS] = ACTIONS(100),
    [anon_sym_EQ] = ACTIONS(100),
    [anon_sym_TILDE] = ACTIONS(100),
    [anon_sym_BQUOTE] = ACTIONS(100),
    [sym_semicolon] = ACTIONS(106),
    [sym_fslash] = ACTIONS(109),
    [sym_bold] = ACTIONS(112),
    [sym_italics] = ACTIONS(112),
    [sym_emdash] = ACTIONS(106),
    [sym_underline] = ACTIONS(112),
    [sym_reference] = ACTIONS(112),
  },
  [13] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(9),
    [sym_fragment] = STATE(48),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(9),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(115),
    [anon_sym_BSLASH] = ACTIONS(115),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [14] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(8),
    [sym_fragment] = STATE(43),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(8),
    [aux_sym_sentence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(117),
    [anon_sym_BSLASH] = ACTIONS(117),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [15] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(17),
    [sym_fragment] = STATE(65),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(17),
    [aux_sym_sentence_repeat1] = STATE(4),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(119),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [16] = {
    [sym_hyphen] = STATE(5),
    [sym_style_marker] = STATE(5),
    [sym_end] = STATE(36),
    [sym_punctuation] = STATE(5),
    [sym__surround] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_parentheses] = STATE(5),
    [sym_other] = STATE(5),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_sentence_repeat1] = STATE(5),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_period] = ACTIONS(31),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_question_mark] = ACTIONS(31),
    [sym_exclamation_point] = ACTIONS(31),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [17] = {
    [sym_hyphen] = STATE(4),
    [sym_style_marker] = STATE(4),
    [sym_sentence] = STATE(12),
    [sym_fragment] = STATE(67),
    [sym_punctuation] = STATE(4),
    [sym__surround] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_parentheses] = STATE(4),
    [sym_other] = STATE(4),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(12),
    [aux_sym_sentence_repeat1] = STATE(4),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(121),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [18] = {
    [sym_hyphen] = STATE(5),
    [sym_style_marker] = STATE(5),
    [sym_end] = STATE(36),
    [sym_punctuation] = STATE(5),
    [sym__surround] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_parentheses] = STATE(5),
    [sym_other] = STATE(5),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_sentence_repeat1] = STATE(5),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_period] = ACTIONS(31),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_question_mark] = ACTIONS(31),
    [sym_exclamation_point] = ACTIONS(31),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [19] = {
    [sym_hyphen] = STATE(16),
    [sym_style_marker] = STATE(16),
    [sym_sentence] = STATE(12),
    [sym_fragment] = STATE(64),
    [sym_punctuation] = STATE(16),
    [sym__surround] = STATE(16),
    [sym_quote] = STATE(16),
    [sym_parentheses] = STATE(16),
    [sym_other] = STATE(16),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(12),
    [aux_sym_sentence_repeat1] = STATE(16),
    [anon_sym_DQUOTE] = ACTIONS(123),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
  [20] = {
    [sym_hyphen] = STATE(16),
    [sym_style_marker] = STATE(16),
    [sym_sentence] = STATE(19),
    [sym_fragment] = STATE(74),
    [sym_punctuation] = STATE(16),
    [sym__surround] = STATE(16),
    [sym_quote] = STATE(16),
    [sym_parentheses] = STATE(16),
    [sym_other] = STATE(16),
    [sym_comma] = STATE(29),
    [sym_colon] = STATE(29),
    [aux_sym_title_repeat1] = STATE(19),
    [aux_sym_sentence_repeat1] = STATE(16),
    [anon_sym_DQUOTE] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_word] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [sym_semicolon] = ACTIONS(33),
    [sym_fslash] = ACTIONS(35),
    [sym_bold] = ACTIONS(37),
    [sym_italics] = ACTIONS(37),
    [sym_emdash] = ACTIONS(33),
    [sym_underline] = ACTIONS(37),
    [sym_reference] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(129), 1,
      anon_sym_DASH,
    STATE(22), 1,
      aux_sym_hyphen_repeat1,
    ACTIONS(131), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(127), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [40] = 4,
    ACTIONS(129), 1,
      anon_sym_DASH,
    STATE(23), 1,
      aux_sym_hyphen_repeat1,
    ACTIONS(135), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(133), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [80] = 4,
    ACTIONS(139), 1,
      anon_sym_DASH,
    STATE(23), 1,
      aux_sym_hyphen_repeat1,
    ACTIONS(142), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(137), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [120] = 2,
    ACTIONS(142), 5,
      anon_sym_DASH,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(137), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [155] = 2,
    ACTIONS(146), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(144), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [189] = 2,
    ACTIONS(150), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(148), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [223] = 2,
    ACTIONS(154), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(152), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [257] = 2,
    ACTIONS(158), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(156), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [291] = 2,
    ACTIONS(162), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(160), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [325] = 2,
    ACTIONS(13), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(11), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [359] = 2,
    ACTIONS(166), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(164), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [393] = 2,
    ACTIONS(170), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(168), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [427] = 2,
    ACTIONS(174), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(172), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [461] = 2,
    ACTIONS(178), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(176), 25,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_period,
      sym_semicolon,
      sym_question_mark,
      sym_exclamation_point,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [495] = 2,
    ACTIONS(182), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(180), 22,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_semicolon,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [526] = 2,
    ACTIONS(186), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym__,
      sym_fslash,
    ACTIONS(184), 22,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_word,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_CARET,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      sym_semicolon,
      sym_bold,
      sym_italics,
      sym_emdash,
      sym_underline,
      sym_reference,
  [557] = 6,
    ACTIONS(188), 1,
      anon_sym_T,
    ACTIONS(190), 1,
      anon_sym_B,
    ACTIONS(192), 1,
      anon_sym_P,
    ACTIONS(194), 1,
      aux_sym_identifier_token1,
    STATE(68), 1,
      sym_identifier,
    ACTIONS(196), 6,
      sym_h1,
      sym_h2,
      sym_h3,
      sym_h4,
      sym_h5,
      sym_h6,
  [581] = 3,
    ACTIONS(5), 1,
      anon_sym_BSLASH,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    STATE(39), 6,
      sym_title,
      sym_heading,
      sym_bookmark,
      sym_paragraph,
      sym_function,
      aux_sym_document_repeat1,
  [596] = 3,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    ACTIONS(202), 1,
      anon_sym_BSLASH,
    STATE(39), 6,
      sym_title,
      sym_heading,
      sym_bookmark,
      sym_paragraph,
      sym_function,
      aux_sym_document_repeat1,
  [611] = 4,
    ACTIONS(205), 1,
      aux_sym_identifier_token1,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_function_repeat1,
    STATE(76), 1,
      sym_parameter,
  [624] = 4,
    ACTIONS(205), 1,
      aux_sym_identifier_token1,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_function_repeat1,
    STATE(63), 1,
      sym_parameter,
  [637] = 4,
    ACTIONS(211), 1,
      aux_sym_identifier_token1,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_function_repeat1,
    STATE(69), 1,
      sym_parameter,
  [650] = 1,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [655] = 1,
    ACTIONS(216), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [660] = 1,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [665] = 1,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [670] = 1,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [675] = 1,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [680] = 1,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [685] = 2,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    STATE(54), 1,
      sym_value,
  [692] = 1,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [697] = 1,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [702] = 1,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [707] = 2,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
  [714] = 2,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      sym_value,
  [721] = 1,
    ACTIONS(234), 2,
      aux_sym_identifier_token1,
      anon_sym_RPAREN,
  [726] = 1,
    ACTIONS(236), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [731] = 2,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
  [738] = 2,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    STATE(77), 1,
      sym_value,
  [745] = 1,
    ACTIONS(240), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [750] = 1,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
  [755] = 1,
    ACTIONS(244), 1,
      sym_word,
  [759] = 1,
    ACTIONS(246), 1,
      anon_sym_COLON,
  [763] = 1,
    ACTIONS(248), 1,
      anon_sym_DQUOTE,
  [767] = 1,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
  [771] = 1,
    ACTIONS(250), 1,
      aux_sym_value_token1,
  [775] = 1,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
  [779] = 1,
    ACTIONS(254), 1,
      anon_sym_LPAREN,
  [783] = 1,
    ACTIONS(256), 1,
      anon_sym_COLON,
  [787] = 1,
    ACTIONS(258), 1,
      anon_sym_DQUOTE,
  [791] = 1,
    ACTIONS(260), 1,
      aux_sym_identifier_token2,
  [795] = 1,
    ACTIONS(262), 1,
      anon_sym_LPAREN,
  [799] = 1,
    ACTIONS(264), 1,
      anon_sym_COLON,
  [803] = 1,
    ACTIONS(266), 1,
      anon_sym_DQUOTE,
  [807] = 1,
    ACTIONS(268), 1,
      aux_sym_identifier_token2,
  [811] = 1,
    ACTIONS(270), 1,
      anon_sym_COLON,
  [815] = 1,
    ACTIONS(230), 1,
      anon_sym_COMMA,
  [819] = 1,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(21)] = 0,
  [SMALL_STATE(22)] = 40,
  [SMALL_STATE(23)] = 80,
  [SMALL_STATE(24)] = 120,
  [SMALL_STATE(25)] = 155,
  [SMALL_STATE(26)] = 189,
  [SMALL_STATE(27)] = 223,
  [SMALL_STATE(28)] = 257,
  [SMALL_STATE(29)] = 291,
  [SMALL_STATE(30)] = 325,
  [SMALL_STATE(31)] = 359,
  [SMALL_STATE(32)] = 393,
  [SMALL_STATE(33)] = 427,
  [SMALL_STATE(34)] = 461,
  [SMALL_STATE(35)] = 495,
  [SMALL_STATE(36)] = 526,
  [SMALL_STATE(37)] = 557,
  [SMALL_STATE(38)] = 581,
  [SMALL_STATE(39)] = 596,
  [SMALL_STATE(40)] = 611,
  [SMALL_STATE(41)] = 624,
  [SMALL_STATE(42)] = 637,
  [SMALL_STATE(43)] = 650,
  [SMALL_STATE(44)] = 655,
  [SMALL_STATE(45)] = 660,
  [SMALL_STATE(46)] = 665,
  [SMALL_STATE(47)] = 670,
  [SMALL_STATE(48)] = 675,
  [SMALL_STATE(49)] = 680,
  [SMALL_STATE(50)] = 685,
  [SMALL_STATE(51)] = 692,
  [SMALL_STATE(52)] = 697,
  [SMALL_STATE(53)] = 702,
  [SMALL_STATE(54)] = 707,
  [SMALL_STATE(55)] = 714,
  [SMALL_STATE(56)] = 721,
  [SMALL_STATE(57)] = 726,
  [SMALL_STATE(58)] = 731,
  [SMALL_STATE(59)] = 738,
  [SMALL_STATE(60)] = 745,
  [SMALL_STATE(61)] = 750,
  [SMALL_STATE(62)] = 755,
  [SMALL_STATE(63)] = 759,
  [SMALL_STATE(64)] = 763,
  [SMALL_STATE(65)] = 767,
  [SMALL_STATE(66)] = 771,
  [SMALL_STATE(67)] = 775,
  [SMALL_STATE(68)] = 779,
  [SMALL_STATE(69)] = 783,
  [SMALL_STATE(70)] = 787,
  [SMALL_STATE(71)] = 791,
  [SMALL_STATE(72)] = 795,
  [SMALL_STATE(73)] = 799,
  [SMALL_STATE(74)] = 803,
  [SMALL_STATE(75)] = 807,
  [SMALL_STATE(76)] = 811,
  [SMALL_STATE(77)] = 815,
  [SMALL_STATE(78)] = 819,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 3, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 3, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bookmark, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bookmark, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sentence_repeat1, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hyphen, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hyphen, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hyphen_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_hyphen_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_hyphen_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_other, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_other, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_colon, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_colon, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comma, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parentheses, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parentheses, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_marker, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_marker, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parentheses, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parentheses, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parentheses, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parentheses, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bookmark, 4, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 5, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 4, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 4, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 3, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [272] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ppr(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
